export type ClockType = "digital" | "analog";
export type SecondsDisplay = "digits" | "ring" | "hidden";
export type LayoutMode = "hero" | "grid";
export type HandStyle = "baton" | "needle" | "neon" | "skeleton";
export type NumeralStyle = "none" | "roman" | "modern" | "dots";

export interface City {
    id: string;
    name: string;
    timezone: string;
    country: string;
    flag: string;
}

export interface ClockSkin {
    id: string;
    name: string;
    type: ClockType;
    category: "digital" | "analog";
    background: string;
    foreground: string;
    accent: string;
    fontFamily: string;
    fontWeight: number;
    glowIntensity: 0 | 1 | 2 | 3;
    motionLevel: 0 | 1 | 2 | 3;
    hasAmbientGradient?: boolean;
}

export interface TimeData {
    hours: number;
    minutes: number;
    seconds: number;
    milliseconds: number;
    hours12: number;
    isPM: boolean;
    date: Date;
}

// Skin definitions
export const DIGITAL_SKINS: ClockSkin[] = [
    {
        id: "zen-minimal",
        name: "Zen Minimal",
        type: "digital",
        category: "digital",
        background: "0 0% 100%",
        foreground: "0 0% 8%",
        accent: "0 0% 20%",
        fontFamily: "var(--font-mono)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "oled-night",
        name: "OLED Night",
        type: "digital",
        category: "digital",
        background: "0 0% 0%",
        foreground: "180 100% 50%",
        accent: "180 100% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
    },
    {
        id: "terminal-green",
        name: "Terminal Green",
        type: "digital",
        category: "digital",
        background: "0 0% 5%",
        foreground: "120 100% 50%",
        accent: "120 100% 40%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "swiss-railway",
        name: "Swiss Railway",
        type: "digital",
        category: "digital",
        background: "0 0% 98%",
        foreground: "0 0% 10%",
        accent: "0 85% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "aurora-glass",
        name: "Aurora Glass",
        type: "digital",
        category: "digital",
        background: "220 30% 15%",
        foreground: "0 0% 95%",
        accent: "280 80% 60%",
        fontFamily: "var(--font-mono)",
        fontWeight: 300,
        glowIntensity: 2,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "cyber-neon",
        name: "Cyber Neon",
        type: "digital",
        category: "digital",
        background: "260 30% 8%",
        foreground: "320 100% 60%",
        accent: "180 100% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 600,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "paper-book",
        name: "Paper Book",
        type: "digital",
        category: "digital",
        background: "40 30% 96%",
        foreground: "30 20% 20%",
        accent: "30 60% 40%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "monochrome-brutal",
        name: "Monochrome Brutal",
        type: "digital",
        category: "digital",
        background: "0 0% 95%",
        foreground: "0 0% 0%",
        accent: "0 0% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 900,
        glowIntensity: 0,
        motionLevel: 0,
    },
    // New digital skins
    {
        id: "retro-lcd",
        name: "Retro LCD",
        type: "digital",
        category: "digital",
        background: "80 25% 75%",
        foreground: "80 30% 20%",
        accent: "80 40% 30%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "sunset-glow",
        name: "Sunset Glow",
        type: "digital",
        category: "digital",
        background: "20 40% 12%",
        foreground: "35 100% 65%",
        accent: "350 80% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "ocean-deep",
        name: "Ocean Deep",
        type: "digital",
        category: "digital",
        background: "210 50% 8%",
        foreground: "195 100% 70%",
        accent: "210 80% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "rose-gold",
        name: "Rose Gold",
        type: "digital",
        category: "digital",
        background: "0 0% 5%",
        foreground: "15 50% 70%",
        accent: "350 40% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "matrix-rain",
        name: "Matrix Rain",
        type: "digital",
        category: "digital",
        background: "120 100% 2%",
        foreground: "120 100% 45%",
        accent: "120 100% 30%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 2,
        motionLevel: 3,
    },
    {
        id: "midnight-purple",
        name: "Midnight Purple",
        type: "digital",
        category: "digital",
        background: "270 30% 8%",
        foreground: "280 60% 75%",
        accent: "260 70% 60%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
    },
    {
        id: "coffee-shop",
        name: "Coffee Shop",
        type: "digital",
        category: "digital",
        background: "30 30% 94%",
        foreground: "25 40% 25%",
        accent: "25 60% 45%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "arctic-ice",
        name: "Arctic Ice",
        type: "digital",
        category: "digital",
        background: "200 20% 98%",
        foreground: "200 50% 30%",
        accent: "195 80% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "spotify-dark",
        name: "Spotify Dark",
        type: "digital",
        category: "digital",
        background: "0 0% 7%",
        foreground: "0 0% 95%",
        accent: "141 73% 42%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "red-ember",
        name: "Red Ember",
        type: "digital",
        category: "digital",
        background: "0 0% 3%",
        foreground: "0 80% 55%",
        accent: "15 90% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 2,
        motionLevel: 2,
    },
    {
        id: "lavender-dream",
        name: "Lavender Dream",
        type: "digital",
        category: "digital",
        background: "270 30% 96%",
        foreground: "270 40% 35%",
        accent: "280 50% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "forest-night",
        name: "Forest Night",
        type: "digital",
        category: "digital",
        background: "150 30% 8%",
        foreground: "140 40% 65%",
        accent: "160 50% 45%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "warm-sand",
        name: "Warm Sand",
        type: "digital",
        category: "digital",
        background: "40 40% 94%",
        foreground: "35 30% 25%",
        accent: "30 70% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "electric-blue",
        name: "Electric Blue",
        type: "digital",
        category: "digital",
        background: "220 40% 6%",
        foreground: "200 100% 60%",
        accent: "220 100% 55%",
        fontFamily: "var(--font-mono)",
        fontWeight: 600,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "newspaper",
        name: "Newspaper",
        type: "digital",
        category: "digital",
        background: "45 20% 92%",
        foreground: "0 0% 10%",
        accent: "0 0% 40%",
        fontFamily: "var(--font-serif)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "synthwave",
        name: "Synthwave",
        type: "digital",
        category: "digital",
        background: "280 60% 10%",
        foreground: "320 100% 70%",
        accent: "50 100% 60%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    // Gradient & Pattern Skins
    {
        id: "sunset-beach",
        name: "Sunset Beach",
        type: "digital",
        category: "digital",
        background: "25 60% 15%",
        foreground: "35 100% 75%",
        accent: "340 80% 65%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "northern-lights",
        name: "Northern Lights",
        type: "digital",
        category: "digital",
        background: "200 40% 8%",
        foreground: "160 80% 65%",
        accent: "180 90% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 300,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "cotton-candy",
        name: "Cotton Candy",
        type: "digital",
        category: "digital",
        background: "300 40% 92%",
        foreground: "280 50% 40%",
        accent: "200 70% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "midnight-galaxy",
        name: "Midnight Galaxy",
        type: "digital",
        category: "digital",
        background: "260 50% 5%",
        foreground: "270 60% 80%",
        accent: "200 100% 70%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "golden-hour",
        name: "Golden Hour",
        type: "digital",
        category: "digital",
        background: "35 50% 92%",
        foreground: "30 60% 25%",
        accent: "40 90% 55%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Dev Theme Skins
    {
        id: "dracula",
        name: "Dracula",
        type: "digital",
        category: "digital",
        background: "231 15% 18%",
        foreground: "326 100% 74%",
        accent: "135 94% 65%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "catppuccin",
        name: "Catppuccin",
        type: "digital",
        category: "digital",
        background: "240 21% 15%",
        foreground: "316 72% 86%",
        accent: "189 71% 73%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "solarized-dark",
        name: "Solarized Dark",
        type: "digital",
        category: "digital",
        background: "192 100% 11%",
        foreground: "186 13% 59%",
        accent: "175 59% 40%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "monokai",
        name: "Monokai",
        type: "digital",
        category: "digital",
        background: "70 8% 15%",
        foreground: "80 76% 53%",
        accent: "338 95% 56%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "nord",
        name: "Nord",
        type: "digital",
        category: "digital",
        background: "220 16% 22%",
        foreground: "218 27% 88%",
        accent: "193 43% 67%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Luxury Skins
    {
        id: "black-onyx",
        name: "Black Onyx",
        type: "digital",
        category: "digital",
        background: "0 0% 2%",
        foreground: "45 90% 55%",
        accent: "45 100% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "marble-white",
        name: "Marble White",
        type: "digital",
        category: "digital",
        background: "0 0% 97%",
        foreground: "0 0% 25%",
        accent: "0 0% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "emerald-luxury",
        name: "Emerald Luxury",
        type: "digital",
        category: "digital",
        background: "160 40% 10%",
        foreground: "45 80% 60%",
        accent: "150 70% 45%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "sapphire-royal",
        name: "Sapphire Royal",
        type: "digital",
        category: "digital",
        background: "220 50% 12%",
        foreground: "220 30% 85%",
        accent: "220 80% 60%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    // Seasonal Skins
    {
        id: "cherry-blossom",
        name: "Cherry Blossom",
        type: "digital",
        category: "digital",
        background: "350 40% 95%",
        foreground: "340 50% 35%",
        accent: "340 70% 65%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "autumn-leaves",
        name: "Autumn Leaves",
        type: "digital",
        category: "digital",
        background: "30 30% 15%",
        foreground: "35 80% 60%",
        accent: "15 90% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "winter-frost",
        name: "Winter Frost",
        type: "digital",
        category: "digital",
        background: "200 30% 96%",
        foreground: "210 40% 35%",
        accent: "200 70% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "summer-vibes",
        name: "Summer Vibes",
        type: "digital",
        category: "digital",
        background: "45 100% 95%",
        foreground: "25 80% 35%",
        accent: "35 100% 55%",
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Retro Skins
    {
        id: "windows-95",
        name: "Windows 95",
        type: "digital",
        category: "digital",
        background: "180 30% 45%",
        foreground: "0 0% 100%",
        accent: "0 0% 75%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "mac-classic",
        name: "Mac Classic",
        type: "digital",
        category: "digital",
        background: "40 20% 90%",
        foreground: "0 0% 5%",
        accent: "0 0% 30%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "commodore",
        name: "Commodore 64",
        type: "digital",
        category: "digital",
        background: "240 60% 25%",
        foreground: "200 80% 70%",
        accent: "200 90% 60%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 1,
        motionLevel: 0,
    },
    {
        id: "game-boy",
        name: "Game Boy",
        type: "digital",
        category: "digital",
        background: "80 30% 60%",
        foreground: "80 50% 15%",
        accent: "80 40% 25%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "blueprint",
        name: "Blueprint",
        type: "digital",
        category: "digital",
        background: "215 70% 25%",
        foreground: "0 0% 95%",
        accent: "200 60% 70%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "grid-paper",
        name: "Grid Paper",
        type: "digital",
        category: "digital",
        background: "0 0% 98%",
        foreground: "210 50% 30%",
        accent: "0 70% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 0,
    },
];

export const ANALOG_SKINS: ClockSkin[] = [
    {
        id: "classic-chrono",
        name: "Classic Chrono",
        type: "analog",
        category: "analog",
        background: "0 0% 98%",
        foreground: "0 0% 10%",
        accent: "0 0% 30%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "minimal-bauhaus",
        name: "Minimal Bauhaus",
        type: "analog",
        category: "analog",
        background: "0 0% 100%",
        foreground: "0 0% 0%",
        accent: "0 85% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "railway-dial",
        name: "Railway Dial",
        type: "analog",
        category: "analog",
        background: "0 0% 100%",
        foreground: "0 0% 5%",
        accent: "0 85% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "skeleton-mechanical",
        name: "Skeleton Mechanical",
        type: "analog",
        category: "analog",
        background: "0 0% 8%",
        foreground: "40 30% 70%",
        accent: "40 50% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 2,
    },
    {
        id: "neon-ring",
        name: "Neon Ring",
        type: "analog",
        category: "analog",
        background: "0 0% 0%",
        foreground: "280 100% 60%",
        accent: "180 100% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 3,
        motionLevel: 2,
    },
    {
        id: "soft-pastel",
        name: "Soft Pastel",
        type: "analog",
        category: "analog",
        background: "340 30% 95%",
        foreground: "340 30% 30%",
        accent: "200 60% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "dark-brass",
        name: "Dark Brass",
        type: "analog",
        category: "analog",
        background: "30 20% 10%",
        foreground: "40 60% 60%",
        accent: "40 70% 45%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "studio-white",
        name: "Studio White",
        type: "analog",
        category: "analog",
        background: "0 0% 100%",
        foreground: "0 0% 20%",
        accent: "0 0% 40%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // New analog skins
    {
        id: "submariner",
        name: "Submariner",
        type: "analog",
        category: "analog",
        background: "0 0% 8%",
        foreground: "0 0% 95%",
        accent: "160 70% 45%",
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "apple-watch",
        name: "Apple Watch",
        type: "analog",
        category: "analog",
        background: "0 0% 0%",
        foreground: "0 0% 100%",
        accent: "32 100% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "pilot-navigator",
        name: "Pilot Navigator",
        type: "analog",
        category: "analog",
        background: "220 20% 12%",
        foreground: "0 0% 95%",
        accent: "35 100% 55%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "rose-gold-luxury",
        name: "Rose Gold Luxury",
        type: "analog",
        category: "analog",
        background: "350 20% 96%",
        foreground: "350 30% 30%",
        accent: "15 50% 60%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "ocean-blue",
        name: "Ocean Blue",
        type: "analog",
        category: "analog",
        background: "210 60% 20%",
        foreground: "0 0% 95%",
        accent: "200 80% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 2,
    },
    {
        id: "vintage-cream",
        name: "Vintage Cream",
        type: "analog",
        category: "analog",
        background: "40 40% 92%",
        foreground: "30 30% 25%",
        accent: "30 50% 40%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "carbon-fiber",
        name: "Carbon Fiber",
        type: "analog",
        category: "analog",
        background: "0 0% 10%",
        foreground: "0 0% 80%",
        accent: "0 85% 55%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "moonlight-silver",
        name: "Moonlight Silver",
        type: "analog",
        category: "analog",
        background: "220 15% 15%",
        foreground: "220 10% 85%",
        accent: "220 20% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "forest-green",
        name: "Forest Green",
        type: "analog",
        category: "analog",
        background: "150 30% 20%",
        foreground: "100 20% 85%",
        accent: "140 50% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "tokyo-night",
        name: "Tokyo Night",
        type: "analog",
        category: "analog",
        background: "260 40% 8%",
        foreground: "340 100% 70%",
        accent: "180 100% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
    },
    {
        id: "desert-sand",
        name: "Desert Sand",
        type: "analog",
        category: "analog",
        background: "35 30% 88%",
        foreground: "30 40% 25%",
        accent: "25 70% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "arctic-explorer",
        name: "Arctic Explorer",
        type: "analog",
        category: "analog",
        background: "200 30% 95%",
        foreground: "200 40% 25%",
        accent: "200 80% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "burgundy-classic",
        name: "Burgundy Classic",
        type: "analog",
        category: "analog",
        background: "350 40% 15%",
        foreground: "40 30% 85%",
        accent: "40 60% 55%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "electric-purple",
        name: "Electric Purple",
        type: "analog",
        category: "analog",
        background: "280 50% 6%",
        foreground: "280 80% 75%",
        accent: "320 100% 60%",
        fontFamily: "var(--font-mono)",
        fontWeight: 500,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "mint-fresh",
        name: "Mint Fresh",
        type: "analog",
        category: "analog",
        background: "160 30% 95%",
        foreground: "160 40% 25%",
        accent: "160 60% 45%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "copper-steampunk",
        name: "Copper Steampunk",
        type: "analog",
        category: "analog",
        background: "25 25% 12%",
        foreground: "30 70% 65%",
        accent: "25 80% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 600,
        glowIntensity: 1,
        motionLevel: 2,
    },
    // Gradient & Pattern Skins
    {
        id: "sunset-beach-analog",
        name: "Sunset Beach",
        type: "analog",
        category: "analog",
        background: "25 60% 15%",
        foreground: "35 100% 75%",
        accent: "340 80% 65%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "northern-lights-analog",
        name: "Northern Lights",
        type: "analog",
        category: "analog",
        background: "200 40% 8%",
        foreground: "160 80% 65%",
        accent: "180 90% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 3,
        motionLevel: 3,
        hasAmbientGradient: true,
    },
    {
        id: "cotton-candy-analog",
        name: "Cotton Candy",
        type: "analog",
        category: "analog",
        background: "300 40% 92%",
        foreground: "280 50% 40%",
        accent: "200 70% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "midnight-galaxy-analog",
        name: "Midnight Galaxy",
        type: "analog",
        category: "analog",
        background: "260 50% 5%",
        foreground: "270 60% 80%",
        accent: "200 100% 70%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 2,
        motionLevel: 2,
        hasAmbientGradient: true,
    },
    {
        id: "golden-hour-analog",
        name: "Golden Hour",
        type: "analog",
        category: "analog",
        background: "35 50% 92%",
        foreground: "30 60% 25%",
        accent: "40 90% 55%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Dev Theme Skins
    {
        id: "dracula-analog",
        name: "Dracula",
        type: "analog",
        category: "analog",
        background: "231 15% 18%",
        foreground: "326 100% 74%",
        accent: "135 94% 65%",
        fontFamily: "var(--font-sans)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "catppuccin-analog",
        name: "Catppuccin",
        type: "analog",
        category: "analog",
        background: "240 21% 15%",
        foreground: "316 72% 86%",
        accent: "189 71% 73%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "nord-analog",
        name: "Nord",
        type: "analog",
        category: "analog",
        background: "220 16% 22%",
        foreground: "218 27% 88%",
        accent: "193 43% 67%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Luxury Skins
    {
        id: "black-onyx-analog",
        name: "Black Onyx",
        type: "analog",
        category: "analog",
        background: "0 0% 2%",
        foreground: "45 90% 55%",
        accent: "45 100% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "marble-white-analog",
        name: "Marble White",
        type: "analog",
        category: "analog",
        background: "0 0% 97%",
        foreground: "0 0% 25%",
        accent: "0 0% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "emerald-luxury-analog",
        name: "Emerald Luxury",
        type: "analog",
        category: "analog",
        background: "160 40% 10%",
        foreground: "45 80% 60%",
        accent: "150 70% 45%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "sapphire-royal-analog",
        name: "Sapphire Royal",
        type: "analog",
        category: "analog",
        background: "220 50% 12%",
        foreground: "220 30% 85%",
        accent: "220 80% 60%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    // Seasonal Skins
    {
        id: "cherry-blossom-analog",
        name: "Cherry Blossom",
        type: "analog",
        category: "analog",
        background: "350 40% 95%",
        foreground: "340 50% 35%",
        accent: "340 70% 65%",
        fontFamily: "var(--font-sans)",
        fontWeight: 400,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "autumn-leaves-analog",
        name: "Autumn Leaves",
        type: "analog",
        category: "analog",
        background: "30 30% 15%",
        foreground: "35 80% 60%",
        accent: "15 90% 50%",
        fontFamily: "var(--font-serif)",
        fontWeight: 500,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "winter-frost-analog",
        name: "Winter Frost",
        type: "analog",
        category: "analog",
        background: "200 30% 96%",
        foreground: "210 40% 35%",
        accent: "200 70% 60%",
        fontFamily: "var(--font-sans)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "summer-vibes-analog",
        name: "Summer Vibes",
        type: "analog",
        category: "analog",
        background: "45 100% 95%",
        foreground: "25 80% 35%",
        accent: "35 100% 55%",
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        glowIntensity: 0,
        motionLevel: 1,
    },
    // Classic Watch Styles
    {
        id: "dive-watch",
        name: "Dive Watch",
        type: "analog",
        category: "analog",
        background: "200 80% 20%",
        foreground: "0 0% 100%",
        accent: "120 70% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "field-military",
        name: "Field Military",
        type: "analog",
        category: "analog",
        background: "100 30% 20%",
        foreground: "60 50% 70%",
        accent: "60 70% 50%",
        fontFamily: "var(--font-mono)",
        fontWeight: 600,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "racing-chrono",
        name: "Racing Chrono",
        type: "analog",
        category: "analog",
        background: "0 0% 5%",
        foreground: "0 0% 95%",
        accent: "0 100% 50%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 1,
    },
    {
        id: "dress-watch",
        name: "Dress Watch",
        type: "analog",
        category: "analog",
        background: "0 0% 100%",
        foreground: "210 30% 20%",
        accent: "210 50% 40%",
        fontFamily: "var(--font-serif)",
        fontWeight: 300,
        glowIntensity: 0,
        motionLevel: 0,
    },
    // Retro/Nostalgia Analog Skins
    {
        id: "windows-95-analog",
        name: "Windows 95",
        type: "analog",
        category: "analog",
        background: "180 60% 35%",
        foreground: "0 0% 100%",
        accent: "0 0% 75%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "mac-classic-analog",
        name: "Mac Classic",
        type: "analog",
        category: "analog",
        background: "40 25% 88%",
        foreground: "0 0% 10%",
        accent: "0 0% 30%",
        fontFamily: "var(--font-sans)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
    {
        id: "commodore-64-analog",
        name: "Commodore 64",
        type: "analog",
        category: "analog",
        background: "220 60% 35%",
        foreground: "200 80% 70%",
        accent: "30 80% 55%",
        fontFamily: "var(--font-mono)",
        fontWeight: 400,
        glowIntensity: 1,
        motionLevel: 1,
    },
    {
        id: "game-boy-analog",
        name: "Game Boy",
        type: "analog",
        category: "analog",
        background: "75 30% 55%",
        foreground: "80 20% 15%",
        accent: "80 25% 25%",
        fontFamily: "var(--font-mono)",
        fontWeight: 700,
        glowIntensity: 0,
        motionLevel: 0,
    },
];

export const ALL_SKINS = [...DIGITAL_SKINS, ...ANALOG_SKINS];
